### ISSUE TITLE
Could you please give more spcified sample ?

### ISSUE THREAD

**Issue by HarborZeng** [rm3l/maoni-email#2]
Totally confused, and I'v got no idea how it works.

I mean, after I added  _compile 'org.rm3l:maoni-email:2.3.1'_ to build.gradle, what confused me is that how to create a Maoni instance as you said "set it as the listener for your Maoni instance" while I don't have one.

Thanks, I am not a native-speaker, so I don't know what Maoni stands for. I will appreciate it if you could help me with this.

**Comment by rm3l** [comment]
Hi @HarborZeng !
`maoni-email` is just a callback implementation for [Maoni](http://maoni.rm3l.org).
So you first need to include Maoni AAR as a dependency in your app. This is what will allow you to construct and start an Maoni instance at the right place within your application workflow (e.g., a button click listener, or a touch of a menu item). 
The Maoni instance will then collect your user feedback and call `maoni-email` for handling the feedback.
See this [page](http://maoni.rm3l.org) for detailed instructions.

BTW, the sample app does leverage maoni-email: https://github.com/rm3l/maoni/tree/master/maoni-sample
